export enum Icon {
    // Item icons

        // Cloth
        BoltOfFrostweave = 'item/cloth/boltOfFrostweave.jpg',
        BoltOfImbuedFrostweave = 'item/cloth/boltOfImbuedFrostweave.jpg',
        Ebonweave = 'item/cloth/ebonweave.jpg',
        EterniumThread = 'item/cloth/eterniumThread.jpg',
        FrostweaveCloth = 'item/cloth/frostweaveCloth.jpg',
        IcewebSpiderSilk = 'item/cloth/icewebSpiderSilk.jpg',
        Moonshroud = 'item/cloth/moonshroud.jpg',
        Spellweave = 'item/cloth/spellweave.jpg',

        // Elemental
        CrystallizedAir = 'item/elemental/crystallizedAir.jpg',
        CrystallizedEarth = 'item/elemental/crystallizedEarth.jpg',
        CrystallizedFire = 'item/elemental/crystallizedFire.jpg',
        CrystallizedLife = 'item/elemental/crystallizedLife.jpg',
        CrystallizedShadow = 'item/elemental/crystallizedShadow.jpg',
        CrystallizedWater = 'item/elemental/crystallizedWater.jpg',
        EternalAir = 'item/elemental/eternalAir.jpg',
        EternalEarth = 'item/elemental/eternalEarth.jpg',
        EternalFire = 'item/elemental/eternalFire.jpg',
        EternalLife = 'item/elemental/eternalLife.jpg',
        EternalShadow = 'item/elemental/eternalShadow.jpg',
        EternalWater = 'item/elemental/eternalWater.jpg',

        // Enchanting
        AbyssCrystal = 'item/enchanting/abyssCrystal.jpg',
        CobaltRod = 'item/enchanting/cobaltRod.jpg',
        DreamShard = 'item/enchanting/dreamShard.jpg',
        GreaterCosmicEssence = 'item/enchanting/greaterCosmicEssence.jpg',
        InfiniteDust = 'item/enchanting/infiniteDust.jpg',
        LesserCosmicEssence = 'item/enchanting/lesserCosmicEssence.jpg',
        RunedCobaltRod = 'item/enchanting/runedCobaltRod.jpg',
        RunedTitaniumRod = 'item/enchanting/runedTitaniumRod.jpg',
        SmallDreamShard = 'item/enchanting/smallDreamShard.jpg',
        TitaniumRod = 'item/enchanting/titaniumRod.jpg',

        // Herb
        AddersTongue = 'item/herb/addersTongue.jpg',
        Deadnettle = 'item/herb/deadnettle.jpg',
        FireLeaf = 'item/herb/fireLeaf.jpg',
        FrostLotus = 'item/herb/frostLotus.jpg',
        Goldclover = 'item/herb/goldclover.jpg',
        Icethorn = 'item/herb/icethorn.jpg',
        Lichbloom = 'item/herb/lichbloom.jpg',
        TalandrasRose = 'item/herb/talandrasRose.jpg',
        TigerLily = 'item/herb/tigerLily.jpg',

        // Inscription
        AlabasterPigment = 'item/inscription/alabasterPigment.jpg',
        AzurePigment = 'item/inscription/azurePigment.jpg',
        BurntPigment = 'item/inscription/burntPigment.jpg',
        CelestialInk = 'item/inscription/celestialInk.jpg',
        DarkflameInk = 'item/inscription/darkflameInk.jpg',
        DawnstarInk = 'item/inscription/dawnstarInk.jpg',
        DuskyPigment = 'item/inscription/duskyPigment.jpg',
        EbonPigment = 'item/inscription/ebonPigment.jpg',
        EmeraldPigment = 'item/inscription/emeraldPigment.jpg',
        EtherealInk = 'item/inscription/etherealInk.jpg',
        FieryInk = 'item/inscription/fieryInk.jpg',
        GoldenPigment = 'item/inscription/goldenPigment.jpg',
        HuntersInk = 'item/inscription/huntersInk.jpg',
        IcyPigment = 'item/inscription/icyPigment.jpg',
        IndigoPigment = 'item/inscription/indigoPigment.jpg',
        InkOfTheSea = 'item/inscription/inkOfTheSea.jpg',
        InkOfTheSky = 'item/inscription/inkOfTheSky.jpg',
        IvoryInk = 'item/inscription/ivoryInk.jpg',
        JadefireInk = 'item/inscription/jadefireInk.jpg',
        LionsInk = 'item/inscription/lionsInk.jpg',
        MidnightInk = 'item/inscription/midnightInk.jpg',
        MoonglowInk = 'item/inscription/moonglowInk.jpg',
        NetherPigment = 'item/inscription/netherPigment.jpg',
        RoyalInk = 'item/inscription/royalInk.jpg',
        RubyPigment = 'item/inscription/rubyPigment.jpg',
        SapphirePigment = 'item/inscription/sapphirePigment.jpg',
        ShimmeringInk = 'item/inscription/shimmeringInk.jpg',
        SilveryPigment = 'item/inscription/silveryPigment.jpg',
        SnowfallInk = 'item/inscription/snowfallInk.jpg',
        VerdantPigment = 'item/inscription/verdantPigment.jpg',
        VioletPigment = 'item/inscription/violetPigment.jpg',

        // Jewelcrafting
        Ametrine = 'item/jewelcrafting/ametrine.jpg',
        AutumnsGlow = 'item/jewelcrafting/autumnsGlow.jpg',
        Bloodstone = 'item/jewelcrafting/bloodstone.jpg',
        CardinalRuby = 'item/jewelcrafting/cardinalRuby.jpg',
        Chalcedony = 'item/jewelcrafting/chalcedony.jpg',
        DarkJade = 'item/jewelcrafting/darkJade.jpg',
        DragonsEye = 'item/jewelcrafting/dragonsEye.jpg',
        Dreadstone = 'item/jewelcrafting/dreadstone.jpg',
        EarthsiegeDiamond = 'item/jewelcrafting/earthsiegeDiamond.jpg',
        EyeOfZul = 'item/jewelcrafting/eyeOfZul.jpg',
        ForestEmerald = 'item/jewelcrafting/forestEmerald.jpg',
        HugeCitrine = 'item/jewelcrafting/hugeCitrine.jpg',
        KingsAmber = 'item/jewelcrafting/kingsAmber.jpg',
        MajesticZircon = 'item/jewelcrafting/majesticZircon.jpg',
        MonarchTopaz = 'item/jewelcrafting/monarchTopaz.jpg',
        NorthseaPearl = 'item/jewelcrafting/northseaPearl.jpg',
        ScarletRuby = 'item/jewelcrafting/scarletRuby.jpg',
        ShadowCrystal = 'item/jewelcrafting/shadowCrystal.jpg',
        SirensTear = 'item/jewelcrafting/sirensTear.jpg',
        SkyflareDiamond = 'item/jewelcrafting/skyflareDiamond.jpg',
        SkySapphire = 'item/jewelcrafting/skySapphire.jpg',
        SunCrystal = 'item/jewelcrafting/sunCrystal.jpg',
        TitaniumPowder = 'item/jewelcrafting/titaniumPowder.jpg',
        TwilightOpal = 'item/jewelcrafting/twilightOpal.jpg',

        // Leather
        ArcticFur = 'item/leather/arcticFur.jpg',
        BoreanLeather = 'item/leather/boreanLeather.jpg',
        BoreanLeatherScraps = 'item/leather/boreanLeatherScraps.jpg',
        HeavyBoreanLeather = 'item/leather/heavyBoreanLeather.jpg',
        IcyDragonscale = 'item/leather/icyDragonscale.jpg',
        JormungarScale = 'item/leather/jormungarScale.jpg',
        NerubianChitin = 'item/leather/nerubianChitin.jpg',

        // Meat
        BarrelheadGoby = 'item/meat/barrelheadGoby.jpg',
        BonescaleSnapper = 'item/meat/bonescaleSnapper.jpg',
        BoreanManOWar = 'item/meat/boreanManOWar.jpg',
        ChilledMeat = 'item/meat/chilledMeat.jpg',
        ChunkOMammoth = 'item/meat/chunkOMammoth.jpg',
        DeepSeaMonsterbelly = 'item/meat/deepSeaMonsterbelly.jpg',
        DragonfinAngelfish = 'item/meat/dragonfinAngelfish.jpg',
        FangtoothHerring = 'item/meat/fangtoothHerring.jpg',
        FountainGoldfish = 'item/meat/fountainGoldfish.jpg',
        GlacialSalmon = 'item/meat/glacialSalmon.jpg',
        GlassfinMinnow = 'item/meat/glassfinMinnow.jpg',
        ImperialMantaRay = 'item/meat/imperialMantaRay.jpg',
        MagicEater = 'item/meat/magicEater.jpg',
        MoonglowCuttlefish = 'item/meat/moonglowCuttlefish.jpg',
        MusselbackSculpin = 'item/meat/musselbackSculpin.jpg',
        Nettlefish = 'item/meat/nettlefish.jpg',
        NorthernEgg = 'item/meat/northernEgg.jpg',
        RhinoMeat = 'item/meat/rhinoMeat.jpg',
        RockfinGrouper = 'item/meat/rockfinGrouper.jpg',
        SewerCarp = 'item/meat/sewerCarp.jpg',
        ShimmeringMinnow = 'item/meat/shimmeringMinnow.jpg',
        ShoveltuskFlank = 'item/meat/shoveltuskFlank.jpg',
        SlipperyEel = 'item/meat/slipperyEel.jpg',
        SucculentClamMeat = 'item/meat/succulentClamMeat.jpg',
        WildTurkey = 'item/meat/wildTurkey.jpg',
        WorgHaunch = 'item/meat/worgHaunch.jpg',
        WormMeat = 'item/meat/wormMeat.jpg',

        // Metal
        CobaltBar = 'item/metal/cobaltBar.jpg',
        CobaltOre = 'item/metal/cobaltOre.jpg',
        SaroniteBar = 'item/metal/saroniteBar.jpg',
        SaroniteOre = 'item/metal/saroniteOre.jpg',
        TitaniumBar = 'item/metal/titaniumBar.jpg',
        TitaniumOre = 'item/metal/titaniumOre.jpg',
        TitansteelBar = 'item/metal/titansteelBar.jpg',

        // Other
        AutumnalHerbs = 'item/other/autumnalHerbs.jpg',
        BountifulBasket = 'item/other/bountifulBasket.jpg',
        BroodingDarkwaterClam = 'item/other/broodingDarkwaterClam.jpg',
        CrusaderOrb = 'item/other/crusaderOrb.jpg',
        DarkwaterClam = 'item/other/darkwaterClam.jpg',
        EnchantedVial = 'item/other/enchantedVial.jpg',
        EnchantingVellum = 'item/other/enchantingVellum.jpg',
        EtherealOil = 'item/other/etherealOil.jpg',
        FrozenOrb = 'item/other/frozenOrb.jpg',
        GiantDarkwaterClam = 'item/other/giantDarkwaterClam.jpg',
        HeavyParchment = 'item/other/heavyParchment.jpg',
        Honey = 'item/other/honey.jpg',
        LightParchment = 'item/other/lightParchment.jpg',
        NorthernSpices = 'item/other/northernSpices.jpg',
        PrimordialSaronite = 'item/other/primordialSaronite.jpg',
        PygmyOil = 'item/other/pygmyOil.jpg',
        PygmySuckerfish = 'item/other/pygmySuckerfish.jpg',
        ReinforcedCrate = 'item/other/reinforcedCrate.jpg',
        ResilientParchment = 'item/other/resilientParchment.jpg',
        RoughParchment = 'item/other/roughParchment.jpg',
        RunedOrb = 'item/other/runedOrb.jpg',

        // Parts
        ElementiumPlatedExhaustPipe = 'item/parts/elementiumPlatedExhaustPipe.jpg',
        FroststeelTube = 'item/parts/froststeelTube.jpg',
        GoblinMachinedPiston = 'item/parts/goblinMachinedPiston.jpg',
        HairTrigger = 'item/parts/hairTrigger.jpg',
        HandfulOfCobaltBolts = 'item/parts/handfulOfCobaltBolts.jpg',
        IndestructibleFrame = 'item/parts/indestructibleFrame.jpg',
        NeoDynamicGearAssembly = 'item/parts/neoDynamicGearAssembly.jpg',
        OverchargedCapacitor = 'item/parts/overchargedCapacitor.jpg',
        SalvagedIronGolemParts = 'item/parts/salvagedIronGolemParts.jpg',
        VolatileBlastingTrigger = 'item/parts/volatileBlastingTrigger.jpg',
        WalnutStock = 'item/parts/walnutStock.jpg',

    // Requirements
    Alchemy = 'req/alchemy.jpg',
    Blacksmithing = 'req/blacksmithing.jpg',
    Enchanting = 'req/enchanting.jpg',
    Engineering = 'req/engineering.jpg',
    Fishing = 'req/fishing.jpg',
    Flying = 'req/flying.png',
    Group = 'req/group.jpg',
    Herbalism = 'req/herbalism.jpg',
    Inscription = 'req/inscription.jpg',
    Jewelcrafting = 'req/jewelcrafting.jpg',
    Leatherworking = 'req/leatherworking.jpg',
    Lockpicking = 'req/lockpicking.jpg',
    Mining = 'req/mining.jpg',
    Quest = 'req/quest.jpg',
    Skinning = 'req/skinning.jpg',
    Stealth = 'req/stealth.jpg',
    Tailoring = 'req/tailoring.jpg',

    // Source types
    Container = 'st/container.jpg',
    Crafted = 'st/crafted.jpg',
    Created = 'st/created.jpg',
    Disenchanted = 'st/disenchanted.jpg',
    Drop = 'st/drop.jpg',
    Fished = 'st/fished.jpg',
    Gathered = 'st/gathered.jpg',
    Milled = 'st/milled.jpg',
    Mined = 'st/mined.jpg',
    Prospected = 'st/prospected.jpg',
    Salvaged = 'st/salvaged.jpg',
    Skinned = 'st/skinned.jpg',
    Sold = 'st/sold.jpg',

    // User preference
    Tracked = 'up/tracked.jpg',
    Abandoned = 'up/abandoned.jpg'
}

export function toAlt(icon: Icon) {
    return icon.toString().slice(0, icon.toString().indexOf('.'));
}